import { flatten } from "@angular/compiler";

export class OrderList {
    id:number= 1; // autoGenerated
    paymentId:string = ""; // Payment
    userId:string = "";
    username:string = "";
    mobileNumber:string = "";
    prescriptionImage:any;
    status:number = -1;
    totalPrice!:number;
}

/* 
status keys 

-1 : inti 
0 : ordered
1 : accepted 
2 : rejected
*/